version: '3.8'
services:
  backend:
    container_name: mern-invoice-generator-backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mern-invoice-generator-mongo
    ports:
      - "27017:27017"
